
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Ticket` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Ticket
 * 
 */
export type TicketModel = runtime.Types.Result.DefaultSelection<Prisma.$TicketPayload>

export type AggregateTicket = {
  _count: TicketCountAggregateOutputType | null
  _min: TicketMinAggregateOutputType | null
  _max: TicketMaxAggregateOutputType | null
}

export type TicketMinAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  status: string | null
  created_at: Date | null
  updated_at: Date | null
  customerId: string | null
  userId: string | null
}

export type TicketMaxAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  status: string | null
  created_at: Date | null
  updated_at: Date | null
  customerId: string | null
  userId: string | null
}

export type TicketCountAggregateOutputType = {
  id: number
  name: number
  description: number
  status: number
  created_at: number
  updated_at: number
  customerId: number
  userId: number
  _all: number
}


export type TicketMinAggregateInputType = {
  id?: true
  name?: true
  description?: true
  status?: true
  created_at?: true
  updated_at?: true
  customerId?: true
  userId?: true
}

export type TicketMaxAggregateInputType = {
  id?: true
  name?: true
  description?: true
  status?: true
  created_at?: true
  updated_at?: true
  customerId?: true
  userId?: true
}

export type TicketCountAggregateInputType = {
  id?: true
  name?: true
  description?: true
  status?: true
  created_at?: true
  updated_at?: true
  customerId?: true
  userId?: true
  _all?: true
}

export type TicketAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Ticket to aggregate.
   */
  where?: Prisma.TicketWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tickets to fetch.
   */
  orderBy?: Prisma.TicketOrderByWithRelationInput | Prisma.TicketOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TicketWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tickets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tickets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Tickets
  **/
  _count?: true | TicketCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TicketMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TicketMaxAggregateInputType
}

export type GetTicketAggregateType<T extends TicketAggregateArgs> = {
      [P in keyof T & keyof AggregateTicket]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTicket[P]>
    : Prisma.GetScalarType<T[P], AggregateTicket[P]>
}




export type TicketGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TicketWhereInput
  orderBy?: Prisma.TicketOrderByWithAggregationInput | Prisma.TicketOrderByWithAggregationInput[]
  by: Prisma.TicketScalarFieldEnum[] | Prisma.TicketScalarFieldEnum
  having?: Prisma.TicketScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TicketCountAggregateInputType | true
  _min?: TicketMinAggregateInputType
  _max?: TicketMaxAggregateInputType
}

export type TicketGroupByOutputType = {
  id: string
  name: string
  description: string
  status: string
  created_at: Date
  updated_at: Date
  customerId: string | null
  userId: string | null
  _count: TicketCountAggregateOutputType | null
  _min: TicketMinAggregateOutputType | null
  _max: TicketMaxAggregateOutputType | null
}

type GetTicketGroupByPayload<T extends TicketGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TicketGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TicketGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TicketGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TicketGroupByOutputType[P]>
      }
    >
  >



export type TicketWhereInput = {
  AND?: Prisma.TicketWhereInput | Prisma.TicketWhereInput[]
  OR?: Prisma.TicketWhereInput[]
  NOT?: Prisma.TicketWhereInput | Prisma.TicketWhereInput[]
  id?: Prisma.StringFilter<"Ticket"> | string
  name?: Prisma.StringFilter<"Ticket"> | string
  description?: Prisma.StringFilter<"Ticket"> | string
  status?: Prisma.StringFilter<"Ticket"> | string
  created_at?: Prisma.DateTimeFilter<"Ticket"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Ticket"> | Date | string
  customerId?: Prisma.StringNullableFilter<"Ticket"> | string | null
  userId?: Prisma.StringNullableFilter<"Ticket"> | string | null
  customer?: Prisma.XOR<Prisma.CustomerNullableScalarRelationFilter, Prisma.CustomerWhereInput> | null
  User?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  comments?: Prisma.TicketCommentListRelationFilter
}

export type TicketOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  customerId?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  customer?: Prisma.CustomerOrderByWithRelationInput
  User?: Prisma.UserOrderByWithRelationInput
  comments?: Prisma.TicketCommentOrderByRelationAggregateInput
}

export type TicketWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TicketWhereInput | Prisma.TicketWhereInput[]
  OR?: Prisma.TicketWhereInput[]
  NOT?: Prisma.TicketWhereInput | Prisma.TicketWhereInput[]
  name?: Prisma.StringFilter<"Ticket"> | string
  description?: Prisma.StringFilter<"Ticket"> | string
  status?: Prisma.StringFilter<"Ticket"> | string
  created_at?: Prisma.DateTimeFilter<"Ticket"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Ticket"> | Date | string
  customerId?: Prisma.StringNullableFilter<"Ticket"> | string | null
  userId?: Prisma.StringNullableFilter<"Ticket"> | string | null
  customer?: Prisma.XOR<Prisma.CustomerNullableScalarRelationFilter, Prisma.CustomerWhereInput> | null
  User?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
  comments?: Prisma.TicketCommentListRelationFilter
}, "id">

export type TicketOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  customerId?: Prisma.SortOrderInput | Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.TicketCountOrderByAggregateInput
  _max?: Prisma.TicketMaxOrderByAggregateInput
  _min?: Prisma.TicketMinOrderByAggregateInput
}

export type TicketScalarWhereWithAggregatesInput = {
  AND?: Prisma.TicketScalarWhereWithAggregatesInput | Prisma.TicketScalarWhereWithAggregatesInput[]
  OR?: Prisma.TicketScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TicketScalarWhereWithAggregatesInput | Prisma.TicketScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Ticket"> | string
  name?: Prisma.StringWithAggregatesFilter<"Ticket"> | string
  description?: Prisma.StringWithAggregatesFilter<"Ticket"> | string
  status?: Prisma.StringWithAggregatesFilter<"Ticket"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Ticket"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"Ticket"> | Date | string
  customerId?: Prisma.StringNullableWithAggregatesFilter<"Ticket"> | string | null
  userId?: Prisma.StringNullableWithAggregatesFilter<"Ticket"> | string | null
}

export type TicketCreateInput = {
  id?: string
  name: string
  description: string
  status: string
  created_at?: Date | string
  updated_at?: Date | string
  customer?: Prisma.CustomerCreateNestedOneWithoutTicketsInput
  User?: Prisma.UserCreateNestedOneWithoutTicketsInput
  comments?: Prisma.TicketCommentCreateNestedManyWithoutTicketInput
}

export type TicketUncheckedCreateInput = {
  id?: string
  name: string
  description: string
  status: string
  created_at?: Date | string
  updated_at?: Date | string
  customerId?: string | null
  userId?: string | null
  comments?: Prisma.TicketCommentUncheckedCreateNestedManyWithoutTicketInput
}

export type TicketUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  customer?: Prisma.CustomerUpdateOneWithoutTicketsNestedInput
  User?: Prisma.UserUpdateOneWithoutTicketsNestedInput
  comments?: Prisma.TicketCommentUpdateManyWithoutTicketNestedInput
}

export type TicketUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  comments?: Prisma.TicketCommentUncheckedUpdateManyWithoutTicketNestedInput
}

export type TicketCreateManyInput = {
  id?: string
  name: string
  description: string
  status: string
  created_at?: Date | string
  updated_at?: Date | string
  customerId?: string | null
  userId?: string | null
}

export type TicketUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TicketUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TicketListRelationFilter = {
  every?: Prisma.TicketWhereInput
  some?: Prisma.TicketWhereInput
  none?: Prisma.TicketWhereInput
}

export type TicketOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TicketCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type TicketMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type TicketMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  status?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type TicketScalarRelationFilter = {
  is?: Prisma.TicketWhereInput
  isNot?: Prisma.TicketWhereInput
}

export type TicketCreateNestedManyWithoutCustomerInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutCustomerInput, Prisma.TicketUncheckedCreateWithoutCustomerInput> | Prisma.TicketCreateWithoutCustomerInput[] | Prisma.TicketUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutCustomerInput | Prisma.TicketCreateOrConnectWithoutCustomerInput[]
  createMany?: Prisma.TicketCreateManyCustomerInputEnvelope
  connect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
}

export type TicketUncheckedCreateNestedManyWithoutCustomerInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutCustomerInput, Prisma.TicketUncheckedCreateWithoutCustomerInput> | Prisma.TicketCreateWithoutCustomerInput[] | Prisma.TicketUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutCustomerInput | Prisma.TicketCreateOrConnectWithoutCustomerInput[]
  createMany?: Prisma.TicketCreateManyCustomerInputEnvelope
  connect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
}

export type TicketUpdateManyWithoutCustomerNestedInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutCustomerInput, Prisma.TicketUncheckedCreateWithoutCustomerInput> | Prisma.TicketCreateWithoutCustomerInput[] | Prisma.TicketUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutCustomerInput | Prisma.TicketCreateOrConnectWithoutCustomerInput[]
  upsert?: Prisma.TicketUpsertWithWhereUniqueWithoutCustomerInput | Prisma.TicketUpsertWithWhereUniqueWithoutCustomerInput[]
  createMany?: Prisma.TicketCreateManyCustomerInputEnvelope
  set?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  disconnect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  delete?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  connect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  update?: Prisma.TicketUpdateWithWhereUniqueWithoutCustomerInput | Prisma.TicketUpdateWithWhereUniqueWithoutCustomerInput[]
  updateMany?: Prisma.TicketUpdateManyWithWhereWithoutCustomerInput | Prisma.TicketUpdateManyWithWhereWithoutCustomerInput[]
  deleteMany?: Prisma.TicketScalarWhereInput | Prisma.TicketScalarWhereInput[]
}

export type TicketUncheckedUpdateManyWithoutCustomerNestedInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutCustomerInput, Prisma.TicketUncheckedCreateWithoutCustomerInput> | Prisma.TicketCreateWithoutCustomerInput[] | Prisma.TicketUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutCustomerInput | Prisma.TicketCreateOrConnectWithoutCustomerInput[]
  upsert?: Prisma.TicketUpsertWithWhereUniqueWithoutCustomerInput | Prisma.TicketUpsertWithWhereUniqueWithoutCustomerInput[]
  createMany?: Prisma.TicketCreateManyCustomerInputEnvelope
  set?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  disconnect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  delete?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  connect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  update?: Prisma.TicketUpdateWithWhereUniqueWithoutCustomerInput | Prisma.TicketUpdateWithWhereUniqueWithoutCustomerInput[]
  updateMany?: Prisma.TicketUpdateManyWithWhereWithoutCustomerInput | Prisma.TicketUpdateManyWithWhereWithoutCustomerInput[]
  deleteMany?: Prisma.TicketScalarWhereInput | Prisma.TicketScalarWhereInput[]
}

export type TicketCreateNestedOneWithoutCommentsInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutCommentsInput, Prisma.TicketUncheckedCreateWithoutCommentsInput>
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutCommentsInput
  connect?: Prisma.TicketWhereUniqueInput
}

export type TicketUpdateOneRequiredWithoutCommentsNestedInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutCommentsInput, Prisma.TicketUncheckedCreateWithoutCommentsInput>
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutCommentsInput
  upsert?: Prisma.TicketUpsertWithoutCommentsInput
  connect?: Prisma.TicketWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TicketUpdateToOneWithWhereWithoutCommentsInput, Prisma.TicketUpdateWithoutCommentsInput>, Prisma.TicketUncheckedUpdateWithoutCommentsInput>
}

export type TicketCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutUserInput, Prisma.TicketUncheckedCreateWithoutUserInput> | Prisma.TicketCreateWithoutUserInput[] | Prisma.TicketUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutUserInput | Prisma.TicketCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.TicketCreateManyUserInputEnvelope
  connect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
}

export type TicketUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutUserInput, Prisma.TicketUncheckedCreateWithoutUserInput> | Prisma.TicketCreateWithoutUserInput[] | Prisma.TicketUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutUserInput | Prisma.TicketCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.TicketCreateManyUserInputEnvelope
  connect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
}

export type TicketUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutUserInput, Prisma.TicketUncheckedCreateWithoutUserInput> | Prisma.TicketCreateWithoutUserInput[] | Prisma.TicketUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutUserInput | Prisma.TicketCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.TicketUpsertWithWhereUniqueWithoutUserInput | Prisma.TicketUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.TicketCreateManyUserInputEnvelope
  set?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  disconnect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  delete?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  connect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  update?: Prisma.TicketUpdateWithWhereUniqueWithoutUserInput | Prisma.TicketUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.TicketUpdateManyWithWhereWithoutUserInput | Prisma.TicketUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.TicketScalarWhereInput | Prisma.TicketScalarWhereInput[]
}

export type TicketUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.TicketCreateWithoutUserInput, Prisma.TicketUncheckedCreateWithoutUserInput> | Prisma.TicketCreateWithoutUserInput[] | Prisma.TicketUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TicketCreateOrConnectWithoutUserInput | Prisma.TicketCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.TicketUpsertWithWhereUniqueWithoutUserInput | Prisma.TicketUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.TicketCreateManyUserInputEnvelope
  set?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  disconnect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  delete?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  connect?: Prisma.TicketWhereUniqueInput | Prisma.TicketWhereUniqueInput[]
  update?: Prisma.TicketUpdateWithWhereUniqueWithoutUserInput | Prisma.TicketUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.TicketUpdateManyWithWhereWithoutUserInput | Prisma.TicketUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.TicketScalarWhereInput | Prisma.TicketScalarWhereInput[]
}

export type TicketCreateWithoutCustomerInput = {
  id?: string
  name: string
  description: string
  status: string
  created_at?: Date | string
  updated_at?: Date | string
  User?: Prisma.UserCreateNestedOneWithoutTicketsInput
  comments?: Prisma.TicketCommentCreateNestedManyWithoutTicketInput
}

export type TicketUncheckedCreateWithoutCustomerInput = {
  id?: string
  name: string
  description: string
  status: string
  created_at?: Date | string
  updated_at?: Date | string
  userId?: string | null
  comments?: Prisma.TicketCommentUncheckedCreateNestedManyWithoutTicketInput
}

export type TicketCreateOrConnectWithoutCustomerInput = {
  where: Prisma.TicketWhereUniqueInput
  create: Prisma.XOR<Prisma.TicketCreateWithoutCustomerInput, Prisma.TicketUncheckedCreateWithoutCustomerInput>
}

export type TicketCreateManyCustomerInputEnvelope = {
  data: Prisma.TicketCreateManyCustomerInput | Prisma.TicketCreateManyCustomerInput[]
  skipDuplicates?: boolean
}

export type TicketUpsertWithWhereUniqueWithoutCustomerInput = {
  where: Prisma.TicketWhereUniqueInput
  update: Prisma.XOR<Prisma.TicketUpdateWithoutCustomerInput, Prisma.TicketUncheckedUpdateWithoutCustomerInput>
  create: Prisma.XOR<Prisma.TicketCreateWithoutCustomerInput, Prisma.TicketUncheckedCreateWithoutCustomerInput>
}

export type TicketUpdateWithWhereUniqueWithoutCustomerInput = {
  where: Prisma.TicketWhereUniqueInput
  data: Prisma.XOR<Prisma.TicketUpdateWithoutCustomerInput, Prisma.TicketUncheckedUpdateWithoutCustomerInput>
}

export type TicketUpdateManyWithWhereWithoutCustomerInput = {
  where: Prisma.TicketScalarWhereInput
  data: Prisma.XOR<Prisma.TicketUpdateManyMutationInput, Prisma.TicketUncheckedUpdateManyWithoutCustomerInput>
}

export type TicketScalarWhereInput = {
  AND?: Prisma.TicketScalarWhereInput | Prisma.TicketScalarWhereInput[]
  OR?: Prisma.TicketScalarWhereInput[]
  NOT?: Prisma.TicketScalarWhereInput | Prisma.TicketScalarWhereInput[]
  id?: Prisma.StringFilter<"Ticket"> | string
  name?: Prisma.StringFilter<"Ticket"> | string
  description?: Prisma.StringFilter<"Ticket"> | string
  status?: Prisma.StringFilter<"Ticket"> | string
  created_at?: Prisma.DateTimeFilter<"Ticket"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Ticket"> | Date | string
  customerId?: Prisma.StringNullableFilter<"Ticket"> | string | null
  userId?: Prisma.StringNullableFilter<"Ticket"> | string | null
}

export type TicketCreateWithoutCommentsInput = {
  id?: string
  name: string
  description: string
  status: string
  created_at?: Date | string
  updated_at?: Date | string
  customer?: Prisma.CustomerCreateNestedOneWithoutTicketsInput
  User?: Prisma.UserCreateNestedOneWithoutTicketsInput
}

export type TicketUncheckedCreateWithoutCommentsInput = {
  id?: string
  name: string
  description: string
  status: string
  created_at?: Date | string
  updated_at?: Date | string
  customerId?: string | null
  userId?: string | null
}

export type TicketCreateOrConnectWithoutCommentsInput = {
  where: Prisma.TicketWhereUniqueInput
  create: Prisma.XOR<Prisma.TicketCreateWithoutCommentsInput, Prisma.TicketUncheckedCreateWithoutCommentsInput>
}

export type TicketUpsertWithoutCommentsInput = {
  update: Prisma.XOR<Prisma.TicketUpdateWithoutCommentsInput, Prisma.TicketUncheckedUpdateWithoutCommentsInput>
  create: Prisma.XOR<Prisma.TicketCreateWithoutCommentsInput, Prisma.TicketUncheckedCreateWithoutCommentsInput>
  where?: Prisma.TicketWhereInput
}

export type TicketUpdateToOneWithWhereWithoutCommentsInput = {
  where?: Prisma.TicketWhereInput
  data: Prisma.XOR<Prisma.TicketUpdateWithoutCommentsInput, Prisma.TicketUncheckedUpdateWithoutCommentsInput>
}

export type TicketUpdateWithoutCommentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  customer?: Prisma.CustomerUpdateOneWithoutTicketsNestedInput
  User?: Prisma.UserUpdateOneWithoutTicketsNestedInput
}

export type TicketUncheckedUpdateWithoutCommentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TicketCreateWithoutUserInput = {
  id?: string
  name: string
  description: string
  status: string
  created_at?: Date | string
  updated_at?: Date | string
  customer?: Prisma.CustomerCreateNestedOneWithoutTicketsInput
  comments?: Prisma.TicketCommentCreateNestedManyWithoutTicketInput
}

export type TicketUncheckedCreateWithoutUserInput = {
  id?: string
  name: string
  description: string
  status: string
  created_at?: Date | string
  updated_at?: Date | string
  customerId?: string | null
  comments?: Prisma.TicketCommentUncheckedCreateNestedManyWithoutTicketInput
}

export type TicketCreateOrConnectWithoutUserInput = {
  where: Prisma.TicketWhereUniqueInput
  create: Prisma.XOR<Prisma.TicketCreateWithoutUserInput, Prisma.TicketUncheckedCreateWithoutUserInput>
}

export type TicketCreateManyUserInputEnvelope = {
  data: Prisma.TicketCreateManyUserInput | Prisma.TicketCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type TicketUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.TicketWhereUniqueInput
  update: Prisma.XOR<Prisma.TicketUpdateWithoutUserInput, Prisma.TicketUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.TicketCreateWithoutUserInput, Prisma.TicketUncheckedCreateWithoutUserInput>
}

export type TicketUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.TicketWhereUniqueInput
  data: Prisma.XOR<Prisma.TicketUpdateWithoutUserInput, Prisma.TicketUncheckedUpdateWithoutUserInput>
}

export type TicketUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.TicketScalarWhereInput
  data: Prisma.XOR<Prisma.TicketUpdateManyMutationInput, Prisma.TicketUncheckedUpdateManyWithoutUserInput>
}

export type TicketCreateManyCustomerInput = {
  id?: string
  name: string
  description: string
  status: string
  created_at?: Date | string
  updated_at?: Date | string
  userId?: string | null
}

export type TicketUpdateWithoutCustomerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  User?: Prisma.UserUpdateOneWithoutTicketsNestedInput
  comments?: Prisma.TicketCommentUpdateManyWithoutTicketNestedInput
}

export type TicketUncheckedUpdateWithoutCustomerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  comments?: Prisma.TicketCommentUncheckedUpdateManyWithoutTicketNestedInput
}

export type TicketUncheckedUpdateManyWithoutCustomerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type TicketCreateManyUserInput = {
  id?: string
  name: string
  description: string
  status: string
  created_at?: Date | string
  updated_at?: Date | string
  customerId?: string | null
}

export type TicketUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  customer?: Prisma.CustomerUpdateOneWithoutTicketsNestedInput
  comments?: Prisma.TicketCommentUpdateManyWithoutTicketNestedInput
}

export type TicketUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  comments?: Prisma.TicketCommentUncheckedUpdateManyWithoutTicketNestedInput
}

export type TicketUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type TicketCountOutputType
 */

export type TicketCountOutputType = {
  comments: number
}

export type TicketCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  comments?: boolean | TicketCountOutputTypeCountCommentsArgs
}

/**
 * TicketCountOutputType without action
 */
export type TicketCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketCountOutputType
   */
  select?: Prisma.TicketCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TicketCountOutputType without action
 */
export type TicketCountOutputTypeCountCommentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TicketCommentWhereInput
}


export type TicketSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  status?: boolean
  created_at?: boolean
  updated_at?: boolean
  customerId?: boolean
  userId?: boolean
  customer?: boolean | Prisma.Ticket$customerArgs<ExtArgs>
  User?: boolean | Prisma.Ticket$UserArgs<ExtArgs>
  comments?: boolean | Prisma.Ticket$commentsArgs<ExtArgs>
  _count?: boolean | Prisma.TicketCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["ticket"]>

export type TicketSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  status?: boolean
  created_at?: boolean
  updated_at?: boolean
  customerId?: boolean
  userId?: boolean
  customer?: boolean | Prisma.Ticket$customerArgs<ExtArgs>
  User?: boolean | Prisma.Ticket$UserArgs<ExtArgs>
}, ExtArgs["result"]["ticket"]>

export type TicketSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  status?: boolean
  created_at?: boolean
  updated_at?: boolean
  customerId?: boolean
  userId?: boolean
  customer?: boolean | Prisma.Ticket$customerArgs<ExtArgs>
  User?: boolean | Prisma.Ticket$UserArgs<ExtArgs>
}, ExtArgs["result"]["ticket"]>

export type TicketSelectScalar = {
  id?: boolean
  name?: boolean
  description?: boolean
  status?: boolean
  created_at?: boolean
  updated_at?: boolean
  customerId?: boolean
  userId?: boolean
}

export type TicketOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "description" | "status" | "created_at" | "updated_at" | "customerId" | "userId", ExtArgs["result"]["ticket"]>
export type TicketInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  customer?: boolean | Prisma.Ticket$customerArgs<ExtArgs>
  User?: boolean | Prisma.Ticket$UserArgs<ExtArgs>
  comments?: boolean | Prisma.Ticket$commentsArgs<ExtArgs>
  _count?: boolean | Prisma.TicketCountOutputTypeDefaultArgs<ExtArgs>
}
export type TicketIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  customer?: boolean | Prisma.Ticket$customerArgs<ExtArgs>
  User?: boolean | Prisma.Ticket$UserArgs<ExtArgs>
}
export type TicketIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  customer?: boolean | Prisma.Ticket$customerArgs<ExtArgs>
  User?: boolean | Prisma.Ticket$UserArgs<ExtArgs>
}

export type $TicketPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Ticket"
  objects: {
    customer: Prisma.$CustomerPayload<ExtArgs> | null
    User: Prisma.$UserPayload<ExtArgs> | null
    comments: Prisma.$TicketCommentPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    description: string
    status: string
    created_at: Date
    updated_at: Date
    customerId: string | null
    userId: string | null
  }, ExtArgs["result"]["ticket"]>
  composites: {}
}

export type TicketGetPayload<S extends boolean | null | undefined | TicketDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TicketPayload, S>

export type TicketCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TicketFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TicketCountAggregateInputType | true
  }

export interface TicketDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Ticket'], meta: { name: 'Ticket' } }
  /**
   * Find zero or one Ticket that matches the filter.
   * @param {TicketFindUniqueArgs} args - Arguments to find a Ticket
   * @example
   * // Get one Ticket
   * const ticket = await prisma.ticket.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TicketFindUniqueArgs>(args: Prisma.SelectSubset<T, TicketFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TicketClient<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Ticket that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TicketFindUniqueOrThrowArgs} args - Arguments to find a Ticket
   * @example
   * // Get one Ticket
   * const ticket = await prisma.ticket.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TicketFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TicketFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TicketClient<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Ticket that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketFindFirstArgs} args - Arguments to find a Ticket
   * @example
   * // Get one Ticket
   * const ticket = await prisma.ticket.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TicketFindFirstArgs>(args?: Prisma.SelectSubset<T, TicketFindFirstArgs<ExtArgs>>): Prisma.Prisma__TicketClient<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Ticket that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketFindFirstOrThrowArgs} args - Arguments to find a Ticket
   * @example
   * // Get one Ticket
   * const ticket = await prisma.ticket.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TicketFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TicketFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TicketClient<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Tickets that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Tickets
   * const tickets = await prisma.ticket.findMany()
   * 
   * // Get first 10 Tickets
   * const tickets = await prisma.ticket.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const ticketWithIdOnly = await prisma.ticket.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TicketFindManyArgs>(args?: Prisma.SelectSubset<T, TicketFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Ticket.
   * @param {TicketCreateArgs} args - Arguments to create a Ticket.
   * @example
   * // Create one Ticket
   * const Ticket = await prisma.ticket.create({
   *   data: {
   *     // ... data to create a Ticket
   *   }
   * })
   * 
   */
  create<T extends TicketCreateArgs>(args: Prisma.SelectSubset<T, TicketCreateArgs<ExtArgs>>): Prisma.Prisma__TicketClient<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Tickets.
   * @param {TicketCreateManyArgs} args - Arguments to create many Tickets.
   * @example
   * // Create many Tickets
   * const ticket = await prisma.ticket.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TicketCreateManyArgs>(args?: Prisma.SelectSubset<T, TicketCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Tickets and returns the data saved in the database.
   * @param {TicketCreateManyAndReturnArgs} args - Arguments to create many Tickets.
   * @example
   * // Create many Tickets
   * const ticket = await prisma.ticket.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Tickets and only return the `id`
   * const ticketWithIdOnly = await prisma.ticket.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TicketCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TicketCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Ticket.
   * @param {TicketDeleteArgs} args - Arguments to delete one Ticket.
   * @example
   * // Delete one Ticket
   * const Ticket = await prisma.ticket.delete({
   *   where: {
   *     // ... filter to delete one Ticket
   *   }
   * })
   * 
   */
  delete<T extends TicketDeleteArgs>(args: Prisma.SelectSubset<T, TicketDeleteArgs<ExtArgs>>): Prisma.Prisma__TicketClient<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Ticket.
   * @param {TicketUpdateArgs} args - Arguments to update one Ticket.
   * @example
   * // Update one Ticket
   * const ticket = await prisma.ticket.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TicketUpdateArgs>(args: Prisma.SelectSubset<T, TicketUpdateArgs<ExtArgs>>): Prisma.Prisma__TicketClient<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Tickets.
   * @param {TicketDeleteManyArgs} args - Arguments to filter Tickets to delete.
   * @example
   * // Delete a few Tickets
   * const { count } = await prisma.ticket.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TicketDeleteManyArgs>(args?: Prisma.SelectSubset<T, TicketDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tickets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Tickets
   * const ticket = await prisma.ticket.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TicketUpdateManyArgs>(args: Prisma.SelectSubset<T, TicketUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tickets and returns the data updated in the database.
   * @param {TicketUpdateManyAndReturnArgs} args - Arguments to update many Tickets.
   * @example
   * // Update many Tickets
   * const ticket = await prisma.ticket.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Tickets and only return the `id`
   * const ticketWithIdOnly = await prisma.ticket.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TicketUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TicketUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Ticket.
   * @param {TicketUpsertArgs} args - Arguments to update or create a Ticket.
   * @example
   * // Update or create a Ticket
   * const ticket = await prisma.ticket.upsert({
   *   create: {
   *     // ... data to create a Ticket
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Ticket we want to update
   *   }
   * })
   */
  upsert<T extends TicketUpsertArgs>(args: Prisma.SelectSubset<T, TicketUpsertArgs<ExtArgs>>): Prisma.Prisma__TicketClient<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Tickets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketCountArgs} args - Arguments to filter Tickets to count.
   * @example
   * // Count the number of Tickets
   * const count = await prisma.ticket.count({
   *   where: {
   *     // ... the filter for the Tickets we want to count
   *   }
   * })
  **/
  count<T extends TicketCountArgs>(
    args?: Prisma.Subset<T, TicketCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TicketCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Ticket.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TicketAggregateArgs>(args: Prisma.Subset<T, TicketAggregateArgs>): Prisma.PrismaPromise<GetTicketAggregateType<T>>

  /**
   * Group by Ticket.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TicketGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TicketGroupByArgs['orderBy'] }
      : { orderBy?: TicketGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TicketGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTicketGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Ticket model
 */
readonly fields: TicketFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Ticket.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TicketClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  customer<T extends Prisma.Ticket$customerArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Ticket$customerArgs<ExtArgs>>): Prisma.Prisma__CustomerClient<runtime.Types.Result.GetResult<Prisma.$CustomerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  User<T extends Prisma.Ticket$UserArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Ticket$UserArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  comments<T extends Prisma.Ticket$commentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Ticket$commentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TicketCommentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Ticket model
 */
export interface TicketFieldRefs {
  readonly id: Prisma.FieldRef<"Ticket", 'String'>
  readonly name: Prisma.FieldRef<"Ticket", 'String'>
  readonly description: Prisma.FieldRef<"Ticket", 'String'>
  readonly status: Prisma.FieldRef<"Ticket", 'String'>
  readonly created_at: Prisma.FieldRef<"Ticket", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"Ticket", 'DateTime'>
  readonly customerId: Prisma.FieldRef<"Ticket", 'String'>
  readonly userId: Prisma.FieldRef<"Ticket", 'String'>
}
    

// Custom InputTypes
/**
 * Ticket findUnique
 */
export type TicketFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
  /**
   * Filter, which Ticket to fetch.
   */
  where: Prisma.TicketWhereUniqueInput
}

/**
 * Ticket findUniqueOrThrow
 */
export type TicketFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
  /**
   * Filter, which Ticket to fetch.
   */
  where: Prisma.TicketWhereUniqueInput
}

/**
 * Ticket findFirst
 */
export type TicketFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
  /**
   * Filter, which Ticket to fetch.
   */
  where?: Prisma.TicketWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tickets to fetch.
   */
  orderBy?: Prisma.TicketOrderByWithRelationInput | Prisma.TicketOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tickets.
   */
  cursor?: Prisma.TicketWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tickets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tickets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tickets.
   */
  distinct?: Prisma.TicketScalarFieldEnum | Prisma.TicketScalarFieldEnum[]
}

/**
 * Ticket findFirstOrThrow
 */
export type TicketFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
  /**
   * Filter, which Ticket to fetch.
   */
  where?: Prisma.TicketWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tickets to fetch.
   */
  orderBy?: Prisma.TicketOrderByWithRelationInput | Prisma.TicketOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Tickets.
   */
  cursor?: Prisma.TicketWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tickets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tickets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Tickets.
   */
  distinct?: Prisma.TicketScalarFieldEnum | Prisma.TicketScalarFieldEnum[]
}

/**
 * Ticket findMany
 */
export type TicketFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
  /**
   * Filter, which Tickets to fetch.
   */
  where?: Prisma.TicketWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Tickets to fetch.
   */
  orderBy?: Prisma.TicketOrderByWithRelationInput | Prisma.TicketOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Tickets.
   */
  cursor?: Prisma.TicketWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Tickets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Tickets.
   */
  skip?: number
  distinct?: Prisma.TicketScalarFieldEnum | Prisma.TicketScalarFieldEnum[]
}

/**
 * Ticket create
 */
export type TicketCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
  /**
   * The data needed to create a Ticket.
   */
  data: Prisma.XOR<Prisma.TicketCreateInput, Prisma.TicketUncheckedCreateInput>
}

/**
 * Ticket createMany
 */
export type TicketCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Tickets.
   */
  data: Prisma.TicketCreateManyInput | Prisma.TicketCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Ticket createManyAndReturn
 */
export type TicketCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * The data used to create many Tickets.
   */
  data: Prisma.TicketCreateManyInput | Prisma.TicketCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Ticket update
 */
export type TicketUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
  /**
   * The data needed to update a Ticket.
   */
  data: Prisma.XOR<Prisma.TicketUpdateInput, Prisma.TicketUncheckedUpdateInput>
  /**
   * Choose, which Ticket to update.
   */
  where: Prisma.TicketWhereUniqueInput
}

/**
 * Ticket updateMany
 */
export type TicketUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Tickets.
   */
  data: Prisma.XOR<Prisma.TicketUpdateManyMutationInput, Prisma.TicketUncheckedUpdateManyInput>
  /**
   * Filter which Tickets to update
   */
  where?: Prisma.TicketWhereInput
  /**
   * Limit how many Tickets to update.
   */
  limit?: number
}

/**
 * Ticket updateManyAndReturn
 */
export type TicketUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * The data used to update Tickets.
   */
  data: Prisma.XOR<Prisma.TicketUpdateManyMutationInput, Prisma.TicketUncheckedUpdateManyInput>
  /**
   * Filter which Tickets to update
   */
  where?: Prisma.TicketWhereInput
  /**
   * Limit how many Tickets to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Ticket upsert
 */
export type TicketUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
  /**
   * The filter to search for the Ticket to update in case it exists.
   */
  where: Prisma.TicketWhereUniqueInput
  /**
   * In case the Ticket found by the `where` argument doesn't exist, create a new Ticket with this data.
   */
  create: Prisma.XOR<Prisma.TicketCreateInput, Prisma.TicketUncheckedCreateInput>
  /**
   * In case the Ticket was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TicketUpdateInput, Prisma.TicketUncheckedUpdateInput>
}

/**
 * Ticket delete
 */
export type TicketDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
  /**
   * Filter which Ticket to delete.
   */
  where: Prisma.TicketWhereUniqueInput
}

/**
 * Ticket deleteMany
 */
export type TicketDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Tickets to delete
   */
  where?: Prisma.TicketWhereInput
  /**
   * Limit how many Tickets to delete.
   */
  limit?: number
}

/**
 * Ticket.customer
 */
export type Ticket$customerArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Customer
   */
  select?: Prisma.CustomerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Customer
   */
  omit?: Prisma.CustomerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerInclude<ExtArgs> | null
  where?: Prisma.CustomerWhereInput
}

/**
 * Ticket.User
 */
export type Ticket$UserArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * Ticket.comments
 */
export type Ticket$commentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketComment
   */
  select?: Prisma.TicketCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketComment
   */
  omit?: Prisma.TicketCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketCommentInclude<ExtArgs> | null
  where?: Prisma.TicketCommentWhereInput
  orderBy?: Prisma.TicketCommentOrderByWithRelationInput | Prisma.TicketCommentOrderByWithRelationInput[]
  cursor?: Prisma.TicketCommentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TicketCommentScalarFieldEnum | Prisma.TicketCommentScalarFieldEnum[]
}

/**
 * Ticket without action
 */
export type TicketDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Ticket
   */
  select?: Prisma.TicketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Ticket
   */
  omit?: Prisma.TicketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketInclude<ExtArgs> | null
}
