
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TicketComment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TicketComment
 * 
 */
export type TicketCommentModel = runtime.Types.Result.DefaultSelection<Prisma.$TicketCommentPayload>

export type AggregateTicketComment = {
  _count: TicketCommentCountAggregateOutputType | null
  _min: TicketCommentMinAggregateOutputType | null
  _max: TicketCommentMaxAggregateOutputType | null
}

export type TicketCommentMinAggregateOutputType = {
  id: string | null
  message: string | null
  created_at: Date | null
  ticketId: string | null
  userId: string | null
}

export type TicketCommentMaxAggregateOutputType = {
  id: string | null
  message: string | null
  created_at: Date | null
  ticketId: string | null
  userId: string | null
}

export type TicketCommentCountAggregateOutputType = {
  id: number
  message: number
  created_at: number
  ticketId: number
  userId: number
  _all: number
}


export type TicketCommentMinAggregateInputType = {
  id?: true
  message?: true
  created_at?: true
  ticketId?: true
  userId?: true
}

export type TicketCommentMaxAggregateInputType = {
  id?: true
  message?: true
  created_at?: true
  ticketId?: true
  userId?: true
}

export type TicketCommentCountAggregateInputType = {
  id?: true
  message?: true
  created_at?: true
  ticketId?: true
  userId?: true
  _all?: true
}

export type TicketCommentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TicketComment to aggregate.
   */
  where?: Prisma.TicketCommentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TicketComments to fetch.
   */
  orderBy?: Prisma.TicketCommentOrderByWithRelationInput | Prisma.TicketCommentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TicketCommentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TicketComments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TicketComments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TicketComments
  **/
  _count?: true | TicketCommentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TicketCommentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TicketCommentMaxAggregateInputType
}

export type GetTicketCommentAggregateType<T extends TicketCommentAggregateArgs> = {
      [P in keyof T & keyof AggregateTicketComment]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTicketComment[P]>
    : Prisma.GetScalarType<T[P], AggregateTicketComment[P]>
}




export type TicketCommentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TicketCommentWhereInput
  orderBy?: Prisma.TicketCommentOrderByWithAggregationInput | Prisma.TicketCommentOrderByWithAggregationInput[]
  by: Prisma.TicketCommentScalarFieldEnum[] | Prisma.TicketCommentScalarFieldEnum
  having?: Prisma.TicketCommentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TicketCommentCountAggregateInputType | true
  _min?: TicketCommentMinAggregateInputType
  _max?: TicketCommentMaxAggregateInputType
}

export type TicketCommentGroupByOutputType = {
  id: string
  message: string
  created_at: Date
  ticketId: string
  userId: string
  _count: TicketCommentCountAggregateOutputType | null
  _min: TicketCommentMinAggregateOutputType | null
  _max: TicketCommentMaxAggregateOutputType | null
}

type GetTicketCommentGroupByPayload<T extends TicketCommentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TicketCommentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TicketCommentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TicketCommentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TicketCommentGroupByOutputType[P]>
      }
    >
  >



export type TicketCommentWhereInput = {
  AND?: Prisma.TicketCommentWhereInput | Prisma.TicketCommentWhereInput[]
  OR?: Prisma.TicketCommentWhereInput[]
  NOT?: Prisma.TicketCommentWhereInput | Prisma.TicketCommentWhereInput[]
  id?: Prisma.StringFilter<"TicketComment"> | string
  message?: Prisma.StringFilter<"TicketComment"> | string
  created_at?: Prisma.DateTimeFilter<"TicketComment"> | Date | string
  ticketId?: Prisma.StringFilter<"TicketComment"> | string
  userId?: Prisma.StringFilter<"TicketComment"> | string
  ticket?: Prisma.XOR<Prisma.TicketScalarRelationFilter, Prisma.TicketWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type TicketCommentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  message?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  ticketId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  ticket?: Prisma.TicketOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type TicketCommentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.TicketCommentWhereInput | Prisma.TicketCommentWhereInput[]
  OR?: Prisma.TicketCommentWhereInput[]
  NOT?: Prisma.TicketCommentWhereInput | Prisma.TicketCommentWhereInput[]
  message?: Prisma.StringFilter<"TicketComment"> | string
  created_at?: Prisma.DateTimeFilter<"TicketComment"> | Date | string
  ticketId?: Prisma.StringFilter<"TicketComment"> | string
  userId?: Prisma.StringFilter<"TicketComment"> | string
  ticket?: Prisma.XOR<Prisma.TicketScalarRelationFilter, Prisma.TicketWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type TicketCommentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  message?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  ticketId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  _count?: Prisma.TicketCommentCountOrderByAggregateInput
  _max?: Prisma.TicketCommentMaxOrderByAggregateInput
  _min?: Prisma.TicketCommentMinOrderByAggregateInput
}

export type TicketCommentScalarWhereWithAggregatesInput = {
  AND?: Prisma.TicketCommentScalarWhereWithAggregatesInput | Prisma.TicketCommentScalarWhereWithAggregatesInput[]
  OR?: Prisma.TicketCommentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TicketCommentScalarWhereWithAggregatesInput | Prisma.TicketCommentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"TicketComment"> | string
  message?: Prisma.StringWithAggregatesFilter<"TicketComment"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"TicketComment"> | Date | string
  ticketId?: Prisma.StringWithAggregatesFilter<"TicketComment"> | string
  userId?: Prisma.StringWithAggregatesFilter<"TicketComment"> | string
}

export type TicketCommentCreateInput = {
  id?: string
  message: string
  created_at?: Date | string
  ticket: Prisma.TicketCreateNestedOneWithoutCommentsInput
  user: Prisma.UserCreateNestedOneWithoutCommentsInput
}

export type TicketCommentUncheckedCreateInput = {
  id?: string
  message: string
  created_at?: Date | string
  ticketId: string
  userId: string
}

export type TicketCommentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ticket?: Prisma.TicketUpdateOneRequiredWithoutCommentsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutCommentsNestedInput
}

export type TicketCommentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ticketId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TicketCommentCreateManyInput = {
  id?: string
  message: string
  created_at?: Date | string
  ticketId: string
  userId: string
}

export type TicketCommentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TicketCommentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ticketId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TicketCommentListRelationFilter = {
  every?: Prisma.TicketCommentWhereInput
  some?: Prisma.TicketCommentWhereInput
  none?: Prisma.TicketCommentWhereInput
}

export type TicketCommentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TicketCommentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  message?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  ticketId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type TicketCommentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  message?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  ticketId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type TicketCommentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  message?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  ticketId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
}

export type TicketCommentCreateNestedManyWithoutTicketInput = {
  create?: Prisma.XOR<Prisma.TicketCommentCreateWithoutTicketInput, Prisma.TicketCommentUncheckedCreateWithoutTicketInput> | Prisma.TicketCommentCreateWithoutTicketInput[] | Prisma.TicketCommentUncheckedCreateWithoutTicketInput[]
  connectOrCreate?: Prisma.TicketCommentCreateOrConnectWithoutTicketInput | Prisma.TicketCommentCreateOrConnectWithoutTicketInput[]
  createMany?: Prisma.TicketCommentCreateManyTicketInputEnvelope
  connect?: Prisma.TicketCommentWhereUniqueInput | Prisma.TicketCommentWhereUniqueInput[]
}

export type TicketCommentUncheckedCreateNestedManyWithoutTicketInput = {
  create?: Prisma.XOR<Prisma.TicketCommentCreateWithoutTicketInput, Prisma.TicketCommentUncheckedCreateWithoutTicketInput> | Prisma.TicketCommentCreateWithoutTicketInput[] | Prisma.TicketCommentUncheckedCreateWithoutTicketInput[]
  connectOrCreate?: Prisma.TicketCommentCreateOrConnectWithoutTicketInput | Prisma.TicketCommentCreateOrConnectWithoutTicketInput[]
  createMany?: Prisma.TicketCommentCreateManyTicketInputEnvelope
  connect?: Prisma.TicketCommentWhereUniqueInput | Prisma.TicketCommentWhereUniqueInput[]
}

export type TicketCommentUpdateManyWithoutTicketNestedInput = {
  create?: Prisma.XOR<Prisma.TicketCommentCreateWithoutTicketInput, Prisma.TicketCommentUncheckedCreateWithoutTicketInput> | Prisma.TicketCommentCreateWithoutTicketInput[] | Prisma.TicketCommentUncheckedCreateWithoutTicketInput[]
  connectOrCreate?: Prisma.TicketCommentCreateOrConnectWithoutTicketInput | Prisma.TicketCommentCreateOrConnectWithoutTicketInput[]
  upsert?: Prisma.TicketCommentUpsertWithWhereUniqueWithoutTicketInput | Prisma.TicketCommentUpsertWithWhereUniqueWithoutTicketInput[]
  createMany?: Prisma.TicketCommentCreateManyTicketInputEnvelope
  set?: Prisma.TicketCommentWhereUniqueInput | Prisma.TicketCommentWhereUniqueInput[]
  disconnect?: Prisma.TicketCommentWhereUniqueInput | Prisma.TicketCommentWhereUniqueInput[]
  delete?: Prisma.TicketCommentWhereUniqueInput | Prisma.TicketCommentWhereUniqueInput[]
  connect?: Prisma.TicketCommentWhereUniqueInput | Prisma.TicketCommentWhereUniqueInput[]
  update?: Prisma.TicketCommentUpdateWithWhereUniqueWithoutTicketInput | Prisma.TicketCommentUpdateWithWhereUniqueWithoutTicketInput[]
  updateMany?: Prisma.TicketCommentUpdateManyWithWhereWithoutTicketInput | Prisma.TicketCommentUpdateManyWithWhereWithoutTicketInput[]
  deleteMany?: Prisma.TicketCommentScalarWhereInput | Prisma.TicketCommentScalarWhereInput[]
}

export type TicketCommentUncheckedUpdateManyWithoutTicketNestedInput = {
  create?: Prisma.XOR<Prisma.TicketCommentCreateWithoutTicketInput, Prisma.TicketCommentUncheckedCreateWithoutTicketInput> | Prisma.TicketCommentCreateWithoutTicketInput[] | Prisma.TicketCommentUncheckedCreateWithoutTicketInput[]
  connectOrCreate?: Prisma.TicketCommentCreateOrConnectWithoutTicketInput | Prisma.TicketCommentCreateOrConnectWithoutTicketInput[]
  upsert?: Prisma.TicketCommentUpsertWithWhereUniqueWithoutTicketInput | Prisma.TicketCommentUpsertWithWhereUniqueWithoutTicketInput[]
  createMany?: Prisma.TicketCommentCreateManyTicketInputEnvelope
  set?: Prisma.TicketCommentWhereUniqueInput | Prisma.TicketCommentWhereUniqueInput[]
  disconnect?: Prisma.TicketCommentWhereUniqueInput | Prisma.TicketCommentWhereUniqueInput[]
  delete?: Prisma.TicketCommentWhereUniqueInput | Prisma.TicketCommentWhereUniqueInput[]
  connect?: Prisma.TicketCommentWhereUniqueInput | Prisma.TicketCommentWhereUniqueInput[]
  update?: Prisma.TicketCommentUpdateWithWhereUniqueWithoutTicketInput | Prisma.TicketCommentUpdateWithWhereUniqueWithoutTicketInput[]
  updateMany?: Prisma.TicketCommentUpdateManyWithWhereWithoutTicketInput | Prisma.TicketCommentUpdateManyWithWhereWithoutTicketInput[]
  deleteMany?: Prisma.TicketCommentScalarWhereInput | Prisma.TicketCommentScalarWhereInput[]
}

export type TicketCommentCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.TicketCommentCreateWithoutUserInput, Prisma.TicketCommentUncheckedCreateWithoutUserInput> | Prisma.TicketCommentCreateWithoutUserInput[] | Prisma.TicketCommentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TicketCommentCreateOrConnectWithoutUserInput | Prisma.TicketCommentCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.TicketCommentCreateManyUserInputEnvelope
  connect?: Prisma.TicketCommentWhereUniqueInput | Prisma.TicketCommentWhereUniqueInput[]
}

export type TicketCommentUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.TicketCommentCreateWithoutUserInput, Prisma.TicketCommentUncheckedCreateWithoutUserInput> | Prisma.TicketCommentCreateWithoutUserInput[] | Prisma.TicketCommentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TicketCommentCreateOrConnectWithoutUserInput | Prisma.TicketCommentCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.TicketCommentCreateManyUserInputEnvelope
  connect?: Prisma.TicketCommentWhereUniqueInput | Prisma.TicketCommentWhereUniqueInput[]
}

export type TicketCommentUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.TicketCommentCreateWithoutUserInput, Prisma.TicketCommentUncheckedCreateWithoutUserInput> | Prisma.TicketCommentCreateWithoutUserInput[] | Prisma.TicketCommentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TicketCommentCreateOrConnectWithoutUserInput | Prisma.TicketCommentCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.TicketCommentUpsertWithWhereUniqueWithoutUserInput | Prisma.TicketCommentUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.TicketCommentCreateManyUserInputEnvelope
  set?: Prisma.TicketCommentWhereUniqueInput | Prisma.TicketCommentWhereUniqueInput[]
  disconnect?: Prisma.TicketCommentWhereUniqueInput | Prisma.TicketCommentWhereUniqueInput[]
  delete?: Prisma.TicketCommentWhereUniqueInput | Prisma.TicketCommentWhereUniqueInput[]
  connect?: Prisma.TicketCommentWhereUniqueInput | Prisma.TicketCommentWhereUniqueInput[]
  update?: Prisma.TicketCommentUpdateWithWhereUniqueWithoutUserInput | Prisma.TicketCommentUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.TicketCommentUpdateManyWithWhereWithoutUserInput | Prisma.TicketCommentUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.TicketCommentScalarWhereInput | Prisma.TicketCommentScalarWhereInput[]
}

export type TicketCommentUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.TicketCommentCreateWithoutUserInput, Prisma.TicketCommentUncheckedCreateWithoutUserInput> | Prisma.TicketCommentCreateWithoutUserInput[] | Prisma.TicketCommentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.TicketCommentCreateOrConnectWithoutUserInput | Prisma.TicketCommentCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.TicketCommentUpsertWithWhereUniqueWithoutUserInput | Prisma.TicketCommentUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.TicketCommentCreateManyUserInputEnvelope
  set?: Prisma.TicketCommentWhereUniqueInput | Prisma.TicketCommentWhereUniqueInput[]
  disconnect?: Prisma.TicketCommentWhereUniqueInput | Prisma.TicketCommentWhereUniqueInput[]
  delete?: Prisma.TicketCommentWhereUniqueInput | Prisma.TicketCommentWhereUniqueInput[]
  connect?: Prisma.TicketCommentWhereUniqueInput | Prisma.TicketCommentWhereUniqueInput[]
  update?: Prisma.TicketCommentUpdateWithWhereUniqueWithoutUserInput | Prisma.TicketCommentUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.TicketCommentUpdateManyWithWhereWithoutUserInput | Prisma.TicketCommentUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.TicketCommentScalarWhereInput | Prisma.TicketCommentScalarWhereInput[]
}

export type TicketCommentCreateWithoutTicketInput = {
  id?: string
  message: string
  created_at?: Date | string
  user: Prisma.UserCreateNestedOneWithoutCommentsInput
}

export type TicketCommentUncheckedCreateWithoutTicketInput = {
  id?: string
  message: string
  created_at?: Date | string
  userId: string
}

export type TicketCommentCreateOrConnectWithoutTicketInput = {
  where: Prisma.TicketCommentWhereUniqueInput
  create: Prisma.XOR<Prisma.TicketCommentCreateWithoutTicketInput, Prisma.TicketCommentUncheckedCreateWithoutTicketInput>
}

export type TicketCommentCreateManyTicketInputEnvelope = {
  data: Prisma.TicketCommentCreateManyTicketInput | Prisma.TicketCommentCreateManyTicketInput[]
  skipDuplicates?: boolean
}

export type TicketCommentUpsertWithWhereUniqueWithoutTicketInput = {
  where: Prisma.TicketCommentWhereUniqueInput
  update: Prisma.XOR<Prisma.TicketCommentUpdateWithoutTicketInput, Prisma.TicketCommentUncheckedUpdateWithoutTicketInput>
  create: Prisma.XOR<Prisma.TicketCommentCreateWithoutTicketInput, Prisma.TicketCommentUncheckedCreateWithoutTicketInput>
}

export type TicketCommentUpdateWithWhereUniqueWithoutTicketInput = {
  where: Prisma.TicketCommentWhereUniqueInput
  data: Prisma.XOR<Prisma.TicketCommentUpdateWithoutTicketInput, Prisma.TicketCommentUncheckedUpdateWithoutTicketInput>
}

export type TicketCommentUpdateManyWithWhereWithoutTicketInput = {
  where: Prisma.TicketCommentScalarWhereInput
  data: Prisma.XOR<Prisma.TicketCommentUpdateManyMutationInput, Prisma.TicketCommentUncheckedUpdateManyWithoutTicketInput>
}

export type TicketCommentScalarWhereInput = {
  AND?: Prisma.TicketCommentScalarWhereInput | Prisma.TicketCommentScalarWhereInput[]
  OR?: Prisma.TicketCommentScalarWhereInput[]
  NOT?: Prisma.TicketCommentScalarWhereInput | Prisma.TicketCommentScalarWhereInput[]
  id?: Prisma.StringFilter<"TicketComment"> | string
  message?: Prisma.StringFilter<"TicketComment"> | string
  created_at?: Prisma.DateTimeFilter<"TicketComment"> | Date | string
  ticketId?: Prisma.StringFilter<"TicketComment"> | string
  userId?: Prisma.StringFilter<"TicketComment"> | string
}

export type TicketCommentCreateWithoutUserInput = {
  id?: string
  message: string
  created_at?: Date | string
  ticket: Prisma.TicketCreateNestedOneWithoutCommentsInput
}

export type TicketCommentUncheckedCreateWithoutUserInput = {
  id?: string
  message: string
  created_at?: Date | string
  ticketId: string
}

export type TicketCommentCreateOrConnectWithoutUserInput = {
  where: Prisma.TicketCommentWhereUniqueInput
  create: Prisma.XOR<Prisma.TicketCommentCreateWithoutUserInput, Prisma.TicketCommentUncheckedCreateWithoutUserInput>
}

export type TicketCommentCreateManyUserInputEnvelope = {
  data: Prisma.TicketCommentCreateManyUserInput | Prisma.TicketCommentCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type TicketCommentUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.TicketCommentWhereUniqueInput
  update: Prisma.XOR<Prisma.TicketCommentUpdateWithoutUserInput, Prisma.TicketCommentUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.TicketCommentCreateWithoutUserInput, Prisma.TicketCommentUncheckedCreateWithoutUserInput>
}

export type TicketCommentUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.TicketCommentWhereUniqueInput
  data: Prisma.XOR<Prisma.TicketCommentUpdateWithoutUserInput, Prisma.TicketCommentUncheckedUpdateWithoutUserInput>
}

export type TicketCommentUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.TicketCommentScalarWhereInput
  data: Prisma.XOR<Prisma.TicketCommentUpdateManyMutationInput, Prisma.TicketCommentUncheckedUpdateManyWithoutUserInput>
}

export type TicketCommentCreateManyTicketInput = {
  id?: string
  message: string
  created_at?: Date | string
  userId: string
}

export type TicketCommentUpdateWithoutTicketInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutCommentsNestedInput
}

export type TicketCommentUncheckedUpdateWithoutTicketInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TicketCommentUncheckedUpdateManyWithoutTicketInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TicketCommentCreateManyUserInput = {
  id?: string
  message: string
  created_at?: Date | string
  ticketId: string
}

export type TicketCommentUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ticket?: Prisma.TicketUpdateOneRequiredWithoutCommentsNestedInput
}

export type TicketCommentUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ticketId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TicketCommentUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  message?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ticketId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type TicketCommentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  message?: boolean
  created_at?: boolean
  ticketId?: boolean
  userId?: boolean
  ticket?: boolean | Prisma.TicketDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["ticketComment"]>

export type TicketCommentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  message?: boolean
  created_at?: boolean
  ticketId?: boolean
  userId?: boolean
  ticket?: boolean | Prisma.TicketDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["ticketComment"]>

export type TicketCommentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  message?: boolean
  created_at?: boolean
  ticketId?: boolean
  userId?: boolean
  ticket?: boolean | Prisma.TicketDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["ticketComment"]>

export type TicketCommentSelectScalar = {
  id?: boolean
  message?: boolean
  created_at?: boolean
  ticketId?: boolean
  userId?: boolean
}

export type TicketCommentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "message" | "created_at" | "ticketId" | "userId", ExtArgs["result"]["ticketComment"]>
export type TicketCommentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ticket?: boolean | Prisma.TicketDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type TicketCommentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ticket?: boolean | Prisma.TicketDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type TicketCommentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ticket?: boolean | Prisma.TicketDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $TicketCommentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TicketComment"
  objects: {
    ticket: Prisma.$TicketPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    message: string
    created_at: Date
    ticketId: string
    userId: string
  }, ExtArgs["result"]["ticketComment"]>
  composites: {}
}

export type TicketCommentGetPayload<S extends boolean | null | undefined | TicketCommentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TicketCommentPayload, S>

export type TicketCommentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TicketCommentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TicketCommentCountAggregateInputType | true
  }

export interface TicketCommentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TicketComment'], meta: { name: 'TicketComment' } }
  /**
   * Find zero or one TicketComment that matches the filter.
   * @param {TicketCommentFindUniqueArgs} args - Arguments to find a TicketComment
   * @example
   * // Get one TicketComment
   * const ticketComment = await prisma.ticketComment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TicketCommentFindUniqueArgs>(args: Prisma.SelectSubset<T, TicketCommentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TicketCommentClient<runtime.Types.Result.GetResult<Prisma.$TicketCommentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TicketComment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TicketCommentFindUniqueOrThrowArgs} args - Arguments to find a TicketComment
   * @example
   * // Get one TicketComment
   * const ticketComment = await prisma.ticketComment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TicketCommentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TicketCommentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TicketCommentClient<runtime.Types.Result.GetResult<Prisma.$TicketCommentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TicketComment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketCommentFindFirstArgs} args - Arguments to find a TicketComment
   * @example
   * // Get one TicketComment
   * const ticketComment = await prisma.ticketComment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TicketCommentFindFirstArgs>(args?: Prisma.SelectSubset<T, TicketCommentFindFirstArgs<ExtArgs>>): Prisma.Prisma__TicketCommentClient<runtime.Types.Result.GetResult<Prisma.$TicketCommentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TicketComment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketCommentFindFirstOrThrowArgs} args - Arguments to find a TicketComment
   * @example
   * // Get one TicketComment
   * const ticketComment = await prisma.ticketComment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TicketCommentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TicketCommentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TicketCommentClient<runtime.Types.Result.GetResult<Prisma.$TicketCommentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TicketComments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketCommentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TicketComments
   * const ticketComments = await prisma.ticketComment.findMany()
   * 
   * // Get first 10 TicketComments
   * const ticketComments = await prisma.ticketComment.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const ticketCommentWithIdOnly = await prisma.ticketComment.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TicketCommentFindManyArgs>(args?: Prisma.SelectSubset<T, TicketCommentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TicketCommentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TicketComment.
   * @param {TicketCommentCreateArgs} args - Arguments to create a TicketComment.
   * @example
   * // Create one TicketComment
   * const TicketComment = await prisma.ticketComment.create({
   *   data: {
   *     // ... data to create a TicketComment
   *   }
   * })
   * 
   */
  create<T extends TicketCommentCreateArgs>(args: Prisma.SelectSubset<T, TicketCommentCreateArgs<ExtArgs>>): Prisma.Prisma__TicketCommentClient<runtime.Types.Result.GetResult<Prisma.$TicketCommentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TicketComments.
   * @param {TicketCommentCreateManyArgs} args - Arguments to create many TicketComments.
   * @example
   * // Create many TicketComments
   * const ticketComment = await prisma.ticketComment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TicketCommentCreateManyArgs>(args?: Prisma.SelectSubset<T, TicketCommentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TicketComments and returns the data saved in the database.
   * @param {TicketCommentCreateManyAndReturnArgs} args - Arguments to create many TicketComments.
   * @example
   * // Create many TicketComments
   * const ticketComment = await prisma.ticketComment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TicketComments and only return the `id`
   * const ticketCommentWithIdOnly = await prisma.ticketComment.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TicketCommentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TicketCommentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TicketCommentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TicketComment.
   * @param {TicketCommentDeleteArgs} args - Arguments to delete one TicketComment.
   * @example
   * // Delete one TicketComment
   * const TicketComment = await prisma.ticketComment.delete({
   *   where: {
   *     // ... filter to delete one TicketComment
   *   }
   * })
   * 
   */
  delete<T extends TicketCommentDeleteArgs>(args: Prisma.SelectSubset<T, TicketCommentDeleteArgs<ExtArgs>>): Prisma.Prisma__TicketCommentClient<runtime.Types.Result.GetResult<Prisma.$TicketCommentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TicketComment.
   * @param {TicketCommentUpdateArgs} args - Arguments to update one TicketComment.
   * @example
   * // Update one TicketComment
   * const ticketComment = await prisma.ticketComment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TicketCommentUpdateArgs>(args: Prisma.SelectSubset<T, TicketCommentUpdateArgs<ExtArgs>>): Prisma.Prisma__TicketCommentClient<runtime.Types.Result.GetResult<Prisma.$TicketCommentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TicketComments.
   * @param {TicketCommentDeleteManyArgs} args - Arguments to filter TicketComments to delete.
   * @example
   * // Delete a few TicketComments
   * const { count } = await prisma.ticketComment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TicketCommentDeleteManyArgs>(args?: Prisma.SelectSubset<T, TicketCommentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TicketComments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketCommentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TicketComments
   * const ticketComment = await prisma.ticketComment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TicketCommentUpdateManyArgs>(args: Prisma.SelectSubset<T, TicketCommentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TicketComments and returns the data updated in the database.
   * @param {TicketCommentUpdateManyAndReturnArgs} args - Arguments to update many TicketComments.
   * @example
   * // Update many TicketComments
   * const ticketComment = await prisma.ticketComment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TicketComments and only return the `id`
   * const ticketCommentWithIdOnly = await prisma.ticketComment.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TicketCommentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TicketCommentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TicketCommentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TicketComment.
   * @param {TicketCommentUpsertArgs} args - Arguments to update or create a TicketComment.
   * @example
   * // Update or create a TicketComment
   * const ticketComment = await prisma.ticketComment.upsert({
   *   create: {
   *     // ... data to create a TicketComment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TicketComment we want to update
   *   }
   * })
   */
  upsert<T extends TicketCommentUpsertArgs>(args: Prisma.SelectSubset<T, TicketCommentUpsertArgs<ExtArgs>>): Prisma.Prisma__TicketCommentClient<runtime.Types.Result.GetResult<Prisma.$TicketCommentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TicketComments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketCommentCountArgs} args - Arguments to filter TicketComments to count.
   * @example
   * // Count the number of TicketComments
   * const count = await prisma.ticketComment.count({
   *   where: {
   *     // ... the filter for the TicketComments we want to count
   *   }
   * })
  **/
  count<T extends TicketCommentCountArgs>(
    args?: Prisma.Subset<T, TicketCommentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TicketCommentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TicketComment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketCommentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TicketCommentAggregateArgs>(args: Prisma.Subset<T, TicketCommentAggregateArgs>): Prisma.PrismaPromise<GetTicketCommentAggregateType<T>>

  /**
   * Group by TicketComment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketCommentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TicketCommentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TicketCommentGroupByArgs['orderBy'] }
      : { orderBy?: TicketCommentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TicketCommentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTicketCommentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TicketComment model
 */
readonly fields: TicketCommentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TicketComment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TicketCommentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  ticket<T extends Prisma.TicketDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TicketDefaultArgs<ExtArgs>>): Prisma.Prisma__TicketClient<runtime.Types.Result.GetResult<Prisma.$TicketPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TicketComment model
 */
export interface TicketCommentFieldRefs {
  readonly id: Prisma.FieldRef<"TicketComment", 'String'>
  readonly message: Prisma.FieldRef<"TicketComment", 'String'>
  readonly created_at: Prisma.FieldRef<"TicketComment", 'DateTime'>
  readonly ticketId: Prisma.FieldRef<"TicketComment", 'String'>
  readonly userId: Prisma.FieldRef<"TicketComment", 'String'>
}
    

// Custom InputTypes
/**
 * TicketComment findUnique
 */
export type TicketCommentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketComment
   */
  select?: Prisma.TicketCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketComment
   */
  omit?: Prisma.TicketCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketCommentInclude<ExtArgs> | null
  /**
   * Filter, which TicketComment to fetch.
   */
  where: Prisma.TicketCommentWhereUniqueInput
}

/**
 * TicketComment findUniqueOrThrow
 */
export type TicketCommentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketComment
   */
  select?: Prisma.TicketCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketComment
   */
  omit?: Prisma.TicketCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketCommentInclude<ExtArgs> | null
  /**
   * Filter, which TicketComment to fetch.
   */
  where: Prisma.TicketCommentWhereUniqueInput
}

/**
 * TicketComment findFirst
 */
export type TicketCommentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketComment
   */
  select?: Prisma.TicketCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketComment
   */
  omit?: Prisma.TicketCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketCommentInclude<ExtArgs> | null
  /**
   * Filter, which TicketComment to fetch.
   */
  where?: Prisma.TicketCommentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TicketComments to fetch.
   */
  orderBy?: Prisma.TicketCommentOrderByWithRelationInput | Prisma.TicketCommentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TicketComments.
   */
  cursor?: Prisma.TicketCommentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TicketComments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TicketComments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TicketComments.
   */
  distinct?: Prisma.TicketCommentScalarFieldEnum | Prisma.TicketCommentScalarFieldEnum[]
}

/**
 * TicketComment findFirstOrThrow
 */
export type TicketCommentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketComment
   */
  select?: Prisma.TicketCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketComment
   */
  omit?: Prisma.TicketCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketCommentInclude<ExtArgs> | null
  /**
   * Filter, which TicketComment to fetch.
   */
  where?: Prisma.TicketCommentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TicketComments to fetch.
   */
  orderBy?: Prisma.TicketCommentOrderByWithRelationInput | Prisma.TicketCommentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TicketComments.
   */
  cursor?: Prisma.TicketCommentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TicketComments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TicketComments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TicketComments.
   */
  distinct?: Prisma.TicketCommentScalarFieldEnum | Prisma.TicketCommentScalarFieldEnum[]
}

/**
 * TicketComment findMany
 */
export type TicketCommentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketComment
   */
  select?: Prisma.TicketCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketComment
   */
  omit?: Prisma.TicketCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketCommentInclude<ExtArgs> | null
  /**
   * Filter, which TicketComments to fetch.
   */
  where?: Prisma.TicketCommentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TicketComments to fetch.
   */
  orderBy?: Prisma.TicketCommentOrderByWithRelationInput | Prisma.TicketCommentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TicketComments.
   */
  cursor?: Prisma.TicketCommentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TicketComments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TicketComments.
   */
  skip?: number
  distinct?: Prisma.TicketCommentScalarFieldEnum | Prisma.TicketCommentScalarFieldEnum[]
}

/**
 * TicketComment create
 */
export type TicketCommentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketComment
   */
  select?: Prisma.TicketCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketComment
   */
  omit?: Prisma.TicketCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketCommentInclude<ExtArgs> | null
  /**
   * The data needed to create a TicketComment.
   */
  data: Prisma.XOR<Prisma.TicketCommentCreateInput, Prisma.TicketCommentUncheckedCreateInput>
}

/**
 * TicketComment createMany
 */
export type TicketCommentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TicketComments.
   */
  data: Prisma.TicketCommentCreateManyInput | Prisma.TicketCommentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TicketComment createManyAndReturn
 */
export type TicketCommentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketComment
   */
  select?: Prisma.TicketCommentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TicketComment
   */
  omit?: Prisma.TicketCommentOmit<ExtArgs> | null
  /**
   * The data used to create many TicketComments.
   */
  data: Prisma.TicketCommentCreateManyInput | Prisma.TicketCommentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketCommentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TicketComment update
 */
export type TicketCommentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketComment
   */
  select?: Prisma.TicketCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketComment
   */
  omit?: Prisma.TicketCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketCommentInclude<ExtArgs> | null
  /**
   * The data needed to update a TicketComment.
   */
  data: Prisma.XOR<Prisma.TicketCommentUpdateInput, Prisma.TicketCommentUncheckedUpdateInput>
  /**
   * Choose, which TicketComment to update.
   */
  where: Prisma.TicketCommentWhereUniqueInput
}

/**
 * TicketComment updateMany
 */
export type TicketCommentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TicketComments.
   */
  data: Prisma.XOR<Prisma.TicketCommentUpdateManyMutationInput, Prisma.TicketCommentUncheckedUpdateManyInput>
  /**
   * Filter which TicketComments to update
   */
  where?: Prisma.TicketCommentWhereInput
  /**
   * Limit how many TicketComments to update.
   */
  limit?: number
}

/**
 * TicketComment updateManyAndReturn
 */
export type TicketCommentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketComment
   */
  select?: Prisma.TicketCommentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TicketComment
   */
  omit?: Prisma.TicketCommentOmit<ExtArgs> | null
  /**
   * The data used to update TicketComments.
   */
  data: Prisma.XOR<Prisma.TicketCommentUpdateManyMutationInput, Prisma.TicketCommentUncheckedUpdateManyInput>
  /**
   * Filter which TicketComments to update
   */
  where?: Prisma.TicketCommentWhereInput
  /**
   * Limit how many TicketComments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketCommentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TicketComment upsert
 */
export type TicketCommentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketComment
   */
  select?: Prisma.TicketCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketComment
   */
  omit?: Prisma.TicketCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketCommentInclude<ExtArgs> | null
  /**
   * The filter to search for the TicketComment to update in case it exists.
   */
  where: Prisma.TicketCommentWhereUniqueInput
  /**
   * In case the TicketComment found by the `where` argument doesn't exist, create a new TicketComment with this data.
   */
  create: Prisma.XOR<Prisma.TicketCommentCreateInput, Prisma.TicketCommentUncheckedCreateInput>
  /**
   * In case the TicketComment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TicketCommentUpdateInput, Prisma.TicketCommentUncheckedUpdateInput>
}

/**
 * TicketComment delete
 */
export type TicketCommentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketComment
   */
  select?: Prisma.TicketCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketComment
   */
  omit?: Prisma.TicketCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketCommentInclude<ExtArgs> | null
  /**
   * Filter which TicketComment to delete.
   */
  where: Prisma.TicketCommentWhereUniqueInput
}

/**
 * TicketComment deleteMany
 */
export type TicketCommentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TicketComments to delete
   */
  where?: Prisma.TicketCommentWhereInput
  /**
   * Limit how many TicketComments to delete.
   */
  limit?: number
}

/**
 * TicketComment without action
 */
export type TicketCommentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketComment
   */
  select?: Prisma.TicketCommentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TicketComment
   */
  omit?: Prisma.TicketCommentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TicketCommentInclude<ExtArgs> | null
}
